### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by steve55792** [t3rmin8tor/pilfer-installer#11]
Hi t3rmin8tor,

Been awhile sinced i used the windows version of pilfer and i see i dont have it on my computer, what  version is it at?How do I set it up? Last question, can it do a folder of links lik rip-record-batch did in the past? Thank you.

                                                                                                                      Steve

**Comment by t3rmin8tor** [comment]
hi steve  v3.0 has just been released <a href="https://github.com/t3rmin8tor/pilfer-installer/releases/download/v3.0/pilfer-install-v3.0.exe">pilfer-installer-v3.0</a>

batch recording is an issue you would have to take up with NapoleonWilson

but  the scheduler should be able to handle multiple recordings (depending on how many ffmpeg processes you could reasonably use)
