### ISSUE TITLE
Problems gettingit to work

### ISSUE THREAD

**Issue by steve55792** [t3rmin8tor/pilfer-installer#12]
Hi t3rmn8tor, how are you doing, hope you had a wonderful Christmas. For some reason i can not get the pilfer working. Dont know if im missing something from the system variables path or not. It looks like:

%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\youtube-dl\bin C:%HOMEPATH%\git\kodi-playercorefactory\bash-scripts-windows; ;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\binC:\pilfer\system\bin
and when im using the cmd prompt I get:  it doesnt recognized as a internal/external command, operable program or batch file. Im i missing something to make it work?    I got the new pilfer installed.

**Comment by t3rmin8tor** [comment]
hi steve 
1 which version of pilfer are you using ?
2 did you do a clean install
3 pilfer installer contains all files needed for instalation 
4 do you see a pilfer icon on the desktop
5 have you double clicked the pilfer icon and configured pilfer 

from the registry path enteries it looks like you still have an old version of rip-record installed 
the new pilfer  program uses python not bash 

also  there is  an error in your paths   ; is missing from the start of the path  

it should be  
%SystemRoot%\system32;
%SystemRoot%;
%SystemRoot%\System32\Wbem;
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;
C:\youtube-dl\bin;
C:%HOMEPATH%\git\kodi-playercorefactory\bash-scripts-windows;
 C:\Program Files\Git\cmd;
C:\Program Files\Git\mingw32\bin;
C:\Program Files\Git\usr\bin;
C:\pilfer\system\bin;

**Comment by steve55792** [comment]
so put this in my path?:
%SystemRoot%\system32;
%SystemRoot%;
%SystemRoot%\System32\Wbem;
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;
C:\youtube-dl\bin;
C:%HOMEPATH%\git\kodi-playercorefactory\bash-scripts-windows;
C:\Program Files\Git\cmd;
C:\Program Files\Git\mingw32\bin;
C:\Program Files\Git\usr\bin;
C:\pilfer\system\bin;

so I did an unistall of pilfer and going to reinstall it, also i got rid of rip-record.

**Comment by t3rmin8tor** [comment]
hi steve yes  notice how every path is seperated with a ;

**Comment by steve55792** [comment]
yep. Im gonna give it a shot to paste it in.

**Comment by steve55792** [comment]
ummm, system variable section, correct?
nevermind, lol. Then all i have to do is reinstall pilfer?

**Comment by t3rmin8tor** [comment]
no steve  in user variables

**Comment by steve55792** [comment]
ok, done it. gonna reinstall pilfer.

**Comment by steve55792** [comment]
First i should ask if anything else i should do before reinstall pilfer?

**Comment by t3rmin8tor** [comment]
hi steve the oly thing you should not do when installing pilfer is change the install path

**Comment by steve55792** [comment]
I did it before i installed the pilfer.
