### ISSUE TITLE
So Im Guessing

### ISSUE THREAD

**Issue by steve55792** [t3rmin8tor/pilfer-installer#13]
Hi t3rmin8tor, How have you been? Im guessing we got delete/unistall the old pilfer before we install the new one?

                                                                                                             Steve

**Comment by t3rmin8tor** [comment]
yes steve

**Comment by steve55792** [comment]
Thank you

**Comment by steve55792** [comment]
Hi t3rmin8tor, another question, how do we setup pilfer to record a channel and i see there is a schedule so a person can schedule a recording.
