### ISSUE TITLE
Cant find python

### ISSUE THREAD

**Issue by steve55792** [t3rmin8tor/pilfer-installer#2]
Hi tr3mn8tor, 
When i try to record or do anything with pilfer I get this message: Windows cant find C:User\ME\Appdata\LOCAL\programs\Python\python36\python.
I know i installed everything. Is the normal Pilfer installer ready? If this is it, I must of screwed up somewhere. It wont save the url or record or anything.

**Comment by vhanla** [comment]
Modify `playercorefactory.xml` file in `%userprofile%\AppData\Roaming\Kodi\userdata\` directory in order to find the correct path where you have python3 installed.
Mine is located at `c:\python3\`
