### ISSUE TITLE
How to use it.

### ISSUE THREAD

**Issue by steve55792** [t3rmin8tor/pilfer-installer#3]
Hi t3min8tor,

How do we use the new pilfer. I got it installed correctly i think. Thank you. Like record a channel ?

**Comment by Topicform** [comment]
Hi Steve, Pilfer 1.4 32bit, it'alk ok for you. Thanks and have a Nice day.

Paolo

Il 09/ott/2017 14:23, "steve55792" <notifications@github.com> ha scritto:

**Comment by Topicform** [comment]
hello jack, one question, if i installo pilfer, appears in the menu of kodi
with the button y ?. me like that there are both the menu in kodi, is of
pilfer that that of rip record. thank you hello.

Il 09/ott/2017 14:26, "Paolo Bordoni" <paolobordoni1@gmail.com> ha scritto:

**Comment by Topicform** [comment]
Hi T3rmin8tor, I would be happy if I developed a Stream all the source for
us Italians, it would be great. There is a SALTS network> Stream all the
Source, it's just for movies and TV series in English. What do you think
about it? Thank you so much.

2017-10-10 14:23 GMT+02:00 Paolo Bordoni <paolobordoni1@gmail.com>:
