### ISSUE TITLE
Unable to record or play

### ISSUE THREAD

**Issue by misspear** [t3rmin8tor/pilfer-installer#4]
Bit of a puzzling one... I uninstalled Rip-Record prior to installing Pilfer with the Windows installer. I installed just as directed and used the GUI to configure Pilfer for my installation. However, when I try to record, whether through the Kodi interface or command line, I get the "Running ffmpeg command:" message for about ten seconds, then the command window disappears and nothing records. When I try to play through MPV Player, I get a prompt window saying "Running mpv command:" that stays on-screen, but nothing else happens. I am not sure why nothing is happening, as I have checked the environment variables and all seems correct. It may be an issue with my build of Windows, but any light that can be shed on this would be helpful.

**Comment by Topicform** [comment]
Hi Jack T3rmin8tor and Misspear it's all ok? News? Hi from Italy _ Regards _ Paolo. :)

**Comment by Topicform** [comment]
Hi Jack, from Kodi all ok. But from Prompt i have this issue. I have windows 8.1 64 bit. i have installed Pilfer 1.4 32bit and playercorefactory put inside userdata. 
![cattura](https://user-images.githubusercontent.com/31699241/31641898-1bd6c2b2-b2e8-11e7-9f9c-bfb67f563fda.PNG)

**Comment by t3rmin8tor** [comment]
hi misspear  could you  copy  the  contents of file here 
so i can  take a look at what the problem is

**Comment by misspear** [comment]
Hi, which file are you referencing?

**Comment by t3rmin8tor** [comment]
the stream that you are attempting to record 
which adoon is it from ?
which channel or  video file is it 
is it an f4m file (running on local proxy) ?

**Comment by PaoloBordoni1** [comment]
Yes is a proxy link.

Paolo

Il 17/ott/2017 13:13, "t3rmin8tor" <notifications@github.com> ha scritto:

**Comment by misspear** [comment]
Hi, the channel link is https://hlslinear-aksc.ams1.media.eurosportplayer.com/ls01/eurosport/linear/channel/EUROSPORT_1_UK-1507581599586/master_wired50_slide.m3u8
From addon Eurosport Player, channel Eurosport 1 (though I've tried other streams as well).
I don't believe it is a proxy link.

**Comment by t3rmin8tor** [comment]
hi give me a few mins ill take a look at whats happening with the link

**Comment by Topicform** [comment]
Hi T3rmin8tor, Pilfer 1.4 32bit on kodi all ok, but from prompt when i
write pilfer - i video url. Txt - t 00:02:00 Nottingham happening. I have
put inside user data the playercorefactory. Thanks for help me. Hi and good
job.

Paolo

Il 17/ott/2017 13:23, "t3rmin8tor" <notifications@github.com> ha scritto:

**Comment by Topicform** [comment]
Ops Nothing happens

Paolo

Il 17/ott/2017 13:30, "Paolo Bordoni" <paolobordoni1@gmail.com> ha scritto:

**Comment by t3rmin8tor** [comment]
![screenshot 5](https://user-images.githubusercontent.com/23662870/31662628-1e393bda-b337-11e7-8b88-3ac2594b999e.png)

hi paul the command needs to be ran in desktop not c:\windows\system32\ as pilfer can not find the path to the file  on the desktop

**Comment by t3rmin8tor** [comment]
hi misspear  sorry that link is not compatable with pilfer 
i have tested from the command line  also within the gui and it fails 
at this moment in time  there is no solution  other than using a different link

**Comment by Topicform** [comment]
Ok i try... See You soon. Y thanks T3rmin8tor.
Paolo

Il 17/ott/2017 13:33, "t3rmin8tor" <notifications@github.com> ha scritto:

**Comment by Topicform** [comment]
Hello T3rmin8tor, I know DOS, and I followed your directions. But when you start the FFMPEG command remains a moment ... and then nothing. Please check my capture and tell me what happened. Thanks for the attention. Hello.
![cattura](https://user-images.githubusercontent.com/31699241/31668366-52695532-b352-11e7-83ad-9128c51b8875.PNG)

**Comment by t3rmin8tor** [comment]
hi paul can you paste me the  link that is in the txt file  video-url-2017-10-17-15-30-53.txt
then i can look at what  is happening

**Comment by Topicform** [comment]
Now that link is deleted, I prepare another one and you can control it. I'm leaving home later. Thanks T3rmin8tor. :)

**Comment by Topicform** [comment]
Hi T3rmin8tor, then I did several tests and I have to say that on demand videos, movies etc ... everything ok. The only problem is on links to IPTV channels to be precise, those links with inside the Proxy ... I attach a link to those who have problems. Thanks for the work you do, always a great CIAO.
[video-url-2017-10-17-23-21-27.txt](https://github.com/t3rmin8tor/pilfer-installer/files/1392695/video-url-2017-10-17-23-21-27.txt)

**Comment by Topicform** [comment]
Hi T3rmin8tor. I would be very happy if I could register to the Prompt Streams of ACESTREAM type by Code. I attach the giant capture that belongs to the url Video file attached. Sorry if I ask you maybe ... the impossible. A heartbeat.
![cattura](https://user-images.githubusercontent.com/31699241/31690831-38afaa0a-b394-11e7-90e4-82e9ae91afbe.PNG)
[video-url-2017-10-17-23-29-50.txt](https://github.com/t3rmin8tor/pilfer-installer/files/1392715/video-url-2017-10-17-23-29-50.txt)

**Comment by t3rmin8tor** [comment]
hi paul  sorry  to say but it isnt possible at the moment to use pilfer with that stream as the address is 
http://127.0.0.1 which means it is a local proxy

**Comment by Topicform** [comment]
Of course, a T3rmin8tor question, you can also have vlc, maybe in a next update, how did you put it in Rip record time? Thanks and 1000 thanks again

**Comment by Topicform** [comment]
Of course, a T3rmin8tor question, you can also have vlc, maybe in a next update, how did you put it in rip record time? Thanks and 1000 thanks again

**Comment by t3rmin8tor** [comment]
there are new updates coming to pilfer but  specific requests should be sent to jack as he  is the core developer

**Comment by steve55792** [comment]
Hi all, new updates?
