### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by cwh060** [t3rmin8tor/pilfer-installer#5]
Not an issue, so much as a thank you for a great set of programs and scripts. The GUI sometimes goes unresponsive and stops, but otherwise the install and programs work great.

**Comment by Topicform** [comment]
I agree. Hi T3rmin8tor.

Paolo

Il 18/ott/2017 16:48, "cwh060" <notifications@github.com> ha scritto:

**Comment by steve55792** [comment]
I agree also, keep up the good work.
