### ISSUE TITLE
Issues in Windows when Kodi is installed from the Windows Store

### ISSUE THREAD

**Issue by DrMaxK** [t3rmin8tor/pilfer-installer#6]
Hello,

When I access the menu in Kodi (pressing the [y] key), the only option that works is saving the url but [Play]  and [Record] don't.

I am running Windows 10 professional and Kodi 17.4, I installed Kodi from the Windows store.
The first problem I had was that when pressing [y] while playing a live stream in Kodi  the menu would only have one option: VideoPlayer(Default) what I found is that my installation of Kodi seems to be part of the problem as there is no %APPDATA%\kodi\userdata in my computer. After some investigation I found that if I had to copy the playercorefactory.xml file into the folder:
C:\Users\MyUser\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\userdata 
fixed the problem with the menu.

I can use the online command to record videos using pilfer, but something is still missing/misconfigured as it doesn't work from Kodi.

**Comment by t3rmin8tor** [comment]
hi DrMaxk

thanks  for raising the issues i will investigate  what is going on with  the  windows store version of kodi and pilfer  and  find a fix for the above issues

**Comment by t3rmin8tor** [comment]
hi DrMaxk 

heres a link to the pilfer version for windows 10 app store version of kodi 
hope this  fixes your issues 
https://github.com/t3rmin8tor/pilfer-installer/releases/download/v1.4/pilfer-1.4-win10-appst.exe
