### ISSUE TITLE
Pilfer

### ISSUE THREAD

**Issue by steve55792** [t3rmin8tor/pilfer-installer#8]
Hi t3rmin8tor, Is there a pilfer for windows x64 still or can the x32 work with the x64 ? I just bought a new computer.

                                                                                   Steve

**Comment by t3rmin8tor** [comment]
hi steve the 32 bit runs on x64 and x32

**Comment by Topicform** [comment]
Hi T3rmin8tor, i wait for new release of Pilfer installerà. Happy new year
end good work. Se You soon.

Il 04/gen/2018 14:46, "t3rmin8tor" <notifications@github.com> ha scritto:

Closed #8 <https://github.com/t3rmin8tor/pilfer-installer/issues/8>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/t3rmin8tor/pilfer-installer/issues/8#event-1409562523>,
or mute the thread

**Comment by t3rmin8tor** [comment]
hi paolo is  there a particular function that you would like to see in pilfer ?

**Comment by Topicform** [comment]
Hi T3rmin8tor, I thank you for the commitment of your Pilfer project. I'd
like the function to save only the audio separately. since I'm very happy
with the video save option. I would very much like (as long as you can do
it ...), to save a file (save video URL) of type AceStream: example: http:
//127.0 .0.1: 6878 / content / a0ebaec9f37290e523c3b6f14e1ecb67d0e60d53 /
0.0597798082391 and then with Pilfer to record. I think Pilfer is a great
job my friend, if you can add the Acestream option for me it's PERFECT.
Thanks, see you soon.

2018-01-04 22:10 GMT+01:00 t3rmin8tor <notifications@github.com>:

**Comment by t3rmin8tor** [comment]
Hi paolo

The option to record  just audio is something that is being worked on 

Acestream integration is an interesting idea  and  should be  looked at
Along with f4m proxy which I’m currently working on it will take  some time
To perfect  the code as  it is quite a complex process

**Comment by Topicform** [comment]
Hi mate this is for you ahahaha

![photo_2018-01-17_12-34-01](https://user-images.githubusercontent.com/31699241/35040984-6e8a0d14-fb83-11e7-8e44-4ca670289d35.jpg)
Hello and thank you T3rmin8tor, I understand that working with Acestream is
complex ... let's say I am very satisfied with the integration of the audio
recording, I wait for the new version of Pilfer and I wish you the best of
Happy New Year and good work. Hello and see you soon. Paul_

2018-01-05 13:57 GMT+01:00 t3rmin8tor <notifications@github.com>:

**Comment by t3rmin8tor** [comment]
pilfer upgrade to version 2.0 is released

**Comment by Topicform** [comment]
Hi T3rmin8tor, I installed the upgrade to Pilfer 2.0 beta.
My situation has improved, I can get the audio file having saved the text file of the URL by typing the letter Y inside Kodi. Very strange that the playercorefactory only works in the 32-bit version, although I have a 64-bit 8.1 Win OS .... but it does not matter, it works perfectly.
The strange thing is that the Pilfer icon in the Desktop, when I click nothing appears, before the upgrade I could click and see the Pilfer window that opened. However, I can get the audio and the video separately. Good job T3rmin8tor, and to hear from you soon. Paul :)

**Comment by t3rmin8tor** [comment]
hi paul thanks for the testing and feedback  ill look into the issues you have raised  and fix them 

for the gui issue can you try this 
open c:\pilfer\system\bin and look for  pilfer-gui.pyw 
double click it  to see if it opens 
if it does can you give me the version number in the top left it should be pilfer v 2
if its still pilfer v 1
open c:\pilfer\system\bin\upgrades\2.0 and copy pilfer-gui.pyw  to
c:\pilfer\system\bin

**Comment by Topicform** [comment]
Thanks to you t3rmin8tor for your work, I await developments, and I salute
you. Bye, see you soon.

2018-01-06 14:06 GMT+01:00 t3rmin8tor <notifications@github.com>:

**Comment by t3rmin8tor** [comment]
hi paul currently working on acestream intergration

**Comment by Topicform** [comment]
Thank you so much for your kindness. Hi T3rmin8tor :)

Paolo

Il 06/gen/2018 16:52, "t3rmin8tor" <notifications@github.com> ha scritto:

hi paul currently working on acestream intergration

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/t3rmin8tor/pilfer-installer/issues/8#issuecomment-355755575>,
or mute the thread

**Comment by Topicform** [comment]
Hi friend, I'll tell you this: I feel very comfortable with Pilfer, it's efficient. The only thing to say is that, I installed the only version .exe the 1.4 to 32bit + Upgrade to 2.0 + 32bit playercorefactory ... It works perfectly, the only thing that the icon on the Desktop of Pilfer, when I click not starts. I Pilfer use it from the command line. I'm more than satisfied. Thanks to you T3rmin8tor. I would be happy if you released version 2.0 as an ExE file, and not as an update .... Thanks mate and good work.﻿

**Comment by t3rmin8tor** [comment]
hi paul  the update to version 2 was  just for testing
thanks for the bug info 
 i will now work on making pilfer 2 a stand alone install with the errors you have mentioned fixed

**Comment by Topicform** [comment]
Hi mate, for now thank you so much for your kindness :)

**Comment by Topicform** [comment]
Hi T3rmin8tor, you are  currently working on acestream intergration ? Perfect mate, i wait for the new installer 2.0_ Thank you so much and good job :)

**Comment by HuwNH** [comment]
Hi t3rmin8tor, thanks for this great work. the 1.4 windows installer doesn't seem to be working for me - when I click on the Desktop icon nothing happens. I tried the manual install but that didn't work either. Any suggestions or help would be much appreciated. Thanks :)

**Comment by t3rmin8tor** [comment]
hi huw could you tell me what  version of windows you are using and i will check  the installer 
also could you tell me  which installer you are using 

eg  pilfer-1.4-kodi-win10-app-store version
    or 
pilfer 1.4 32bit official release

**Comment by steve55792** [comment]
Windows 7
    On Thursday, March 8, 2018, 12:15:11 PM CST, t3rmin8tor <notifications@github.com> wrote:  
 
 
hi huw could you tell me what version of windows you are using and i will check the installer

**Comment by HuwNH** [comment]
hi t3rmin8tor, I am running windows 10 (version 1079) and was trying to use the pilfer 1.4 32bit official release. Should I try the app-store version? Thanks so much for the help. Cheers,

**Comment by t3rmin8tor** [comment]
hi huw are you using the windows 10 app store vesion of kodi or the windows 32 bit standard install
3 reasons 
(assuming you have kodi installed )
1 the pilfer 1.4-kodi-win10-app-store-version  will not work with kodi 32bit standard install
2 pilfer 1.4 32 bit official release will not work with  the app-store version of kodi 
3 version 1079 of windows has been known to not play nice with  the standard kodi install and  pilfer official release 

my suggestion would be  to
1 uninstall the standard kodi 
2 uninstall pilfer completely
3 install  the windows 10 kodi app-store version
4 install the win-10-app-version of pilfer

**Comment by HuwNH** [comment]
hi terminator, that makes a lot of sense. Will try this over the weekend and let you know how it goes. Thanks again for the help on this!

**Comment by HuwNH** [comment]
hi t3rmin8tor, managed to get it working from the command line and within Kodi - really appreciate the help!
